name: getx_server_demo
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies:
  get_server: ^1.1.1
